vim.opt.number = true -- show line numbers
vim.opt.tabstop = 2 -- number of spaces that a <Tab> in the file counts for
vim.opt.softtabstop = 2 -- number of spaces that a <Tab> counts for while performing editing operations, like inserting a <Tab> or using <BS>
vim.opt.shiftwidth = 2 -- number of spaces to use for each step of (auto)indent
vim.opt.expandtab = true -- in Insert mode: Use the appropriate number of spaces to insert a <Tab>
vim.opt.swapfile = false -- don't use swapfile for a buffer
vim.opt.backup = false -- don't write backups for a buffer
vim.opt.undofile = true -- automatically saves undo history
vim.opt.clipboard = 'unnamedplus' -- use system clipboard
vim.opt.signcolumn = 'yes' -- show sign columns (even blank)
vim.opt.shortmess:append 'I' -- don't show nvim intro message
vim.opt.showmode = false -- show mode in last line
vim.opt.showbreak = '↪' -- string to put at the start of lines that have been wrapped
vim.opt.ignorecase = true -- ignore case in search patterns
vim.opt.smartcase = true -- override ignorecase when search pattern has uppercase
vim.opt.shiftround = true -- round indent to multiple of 'shiftwidth'.  Applies to > and < commands
vim.opt.updatetime = 100 -- if this many milliseconds nothing is typed the swap file will be written to disk. Also used for the CursorHold autocommand event
vim.opt.scrolloff = 12 -- minimal number of screen lines to keep above and below the cursor
vim.opt.breakindent = true -- enable break indent
vim.opt.cursorline = true -- highlight current line
vim.opt.splitright = true -- open vertical splits to the right
vim.opt.splitbelow = true -- open horizontal splits below
vim.opt.ruler = false -- Don't show the ruler
vim.opt.showcmd = false -- Don't show the command in the last line
vim.opt.writebackup = false -- if a file is being edited by another program (or was written to file while editing with another program), it is not allowed to be edited
vim.opt.title = true -- set the title of window to the value of the titlestring
