vim.wo.number = true -- show line numbers
vim.o.relativenumber = true -- show relative numbers
vim.bo.tabstop = 4 -- number of spaces that a <Tab> in the file counts for
vim.bo.softtabstop = 4 -- number of spaces that a <Tab> counts for while performing editing operations, like inserting a <Tab> or using <BS>
vim.bo.shiftwidth = 4 -- number of spaces to use for each step of (auto)indent
vim.bo.expandtab = true -- in Insert mode: Use the appropriate number of spaces to insert a <Tab>
vim.o.swapfile = false -- don't use swapfile for a buffer
vim.o.backup = false -- don't write backups for a buffer
vim.bo.undofile = true -- automatically saves undo history
vim.o.clipboard = 'unnamedplus' -- use system clipboard
vim.o.signcolumn = 'yes' -- show sign columns (even blank)
vim.o.shortmess = vim.o.shortmess..'I' -- don't show nvim intro message
vim.o.termguicolors = true -- enables 24-bit RGB color in the TUI
vim.o.showmode = false -- show mode in last line
vim.o.showbreak = '↪' -- string to put at the start of lines that have been wrapped
vim.o.ignorecase = true -- ignore case in search patterns
vim.o.shiftround = true -- round indent to multiple of 'shiftwidth'.  Applies to > and < commands
vim.o.updatetime = 300 -- if this many milliseconds nothing is typed the swap file will be written to disk. Also used for the CursorHold autocommand event
vim.o.scrolloff = 12 -- minimal number of screen lines to keep above and below the cursor
vim.bo.smartindent = true -- do smart autoindenting when starting a new line
vim.o.incsearch = true -- while typing a search command, show where the pattern, as it was typed so far, matches.
vim.o.hlsearch = false  -- set highlight on search
vim.o.breakindent = true -- enable break indent
