local map = vim.keymap.set
map('v', 'J', [[:m '>+1<CR>gv=gv]], { desc = 'Move lines down respecting indentation' })
map('v', 'K', [[:m '<-2<CR>gv=gv]], { desc = 'Move lines up respecting indentation' })
map('n', 'J', [[mzJ`z]], { desc = 'Join lines without move cursor' })
map('n', '<C-d>', [[<C-d>zz]], { desc = 'Scroll window downwards in the buffer' })
map('n', '<C-u>', [[<C-u>zz]], { desc = 'Scroll window upwards in the buffer' })
map('n', 'n', [[nzzzv]], { desc = "Search will center on the line it's found in" })
map('n', 'N', [[Nzzzv]], { desc = "Search will center on the line it's found in" })
map('n', ']q', [[<cmd>cnext<CR>zz]], { desc = 'Navigate next in quickfix list' })
map('n', '[q', [[<cmd>cprev<CR>zz]], { desc = 'Navigate previous in quickfix list' })
map('n', ']l', [[<cmd>lnext<CR>zz]], { desc = 'Navigate next in location list' })
map('n', '[l', [[<cmd>lprev<CR>zz]], { desc = 'Navigate previous in location list' })
map('n', '<leader>r', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]], { desc = 'Search and replace' })
map('n', '<leader>x', [[<cmd>!chmod +x %<CR>]], { desc = 'Allow execution permission' })
map('n', '<leader>-', vim.cmd.split, { desc = 'Split horizontally' })
map('n', '<leader>|', vim.cmd.vsplit, { desc = 'Split vertically' })
map('n', '[b', vim.cmd.bp, { desc = 'Move to previous buffer' })
map('n', ']b', vim.cmd.bn, { desc = 'Move to next buffer' })
map('n', '<leader>q', function()
  local bufnr = vim.api.nvim_get_current_buf()
  pcall(vim.cmd.bp)
  vim.cmd.bd(bufnr)
end, { desc = 'Close current buffer' })
map('n', '<leader>.', [[<Cmd>lcd %:p:h<CR>]], { desc = 'Set current file directory as working directory' })
map('v', '<', [[<gv]], { desc = 'Unindent and reselect' })
map('v', '>', [[>gv]], { desc = 'Indent and reselect' })
