local map = vim.keymap.set

map('v', 'J', [[:m '>+1<CR>gv=gv]], { desc = 'Move lines down respecting indentation' })
map('v', 'K', [[:m '<-2<CR>gv=gv]], { desc = 'Move lines up respecting indentation' })
map('n', '<leader>r', [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]], { desc = 'Search and replace' })
map('n', '<leader>-', vim.cmd.split, { desc = 'Split horizontally' })
map('n', '<leader>|', vim.cmd.vsplit, { desc = 'Split vertically' })
map('n', '<leader>c', function()
  local bufnr = vim.api.nvim_get_current_buf()
  pcall(vim.cmd.bp)
  vim.cmd.bd(bufnr)
end, { desc = 'Close current buffer' })
map('n', '<leader>.', [[<Cmd>lcd %:p:h<CR>]], { desc = 'Set current file directory as working directory' })
map('v', '<', [[<gv]], { desc = 'Unindent and reselect' })
map('v', '>', [[>gv]], { desc = 'Indent and reselect' })
